# Generated by Django 3.0.5 on 2020-06-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200618_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/thumbnail.jpg', upload_to='images/', verbose_name='Image'),
        ),
    ]
