# Generated by Django 3.0.5 on 2020-06-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
