# Generated by Django 3.0.5 on 2020-06-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='UPES ACM & ACM-W Member'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default='images/profiledp.jpg', upload_to='profilepic/'),
        ),
    ]
